### PR TITLE
psi4 build and keyword integration

### PR DESCRIPTION
**Pull request by loriab**
- [x] Separates out CMake interject libraries so that the exe can be built static and with old glibc
- [x] Warns about what to do when hit gcc/flto error (https://github.com/psi4/psi4/issues/414). CMake variables will be passed through from psi4
- [x] Moved keywords to chemps2 bin ones according to https://github.com/psi4/psi4/issues/150#issuecomment-228951911

- [x] **Ready to go.** When these are in, could I get a version tag bump (patch level is fine) to have psi4 pull from?

### CODE REVIEW

**Comment by SebWouters** [comment]
Hi Lori,

In as far you would like to copy some documentation on CASPT2 keywords, I have updated the sphinx documentation:

http://sebwouters.github.io/CheMPS2/caspt2.html

Best wishes,
Sebastian

**Comment by loriab** [comment]
Thanks for the updated docs, @SebWouters . The psi4 PR on CheMPS2 is at https://github.com/psi4/psi4/pull/427/files . Apart from [read_options](https://github.com/loriab/psi4/blob/0267e9f4a2a850b607028890bb574d1d9fc05955/src/bin/psi4/read_options.cc#L4439-L4536) documenting the keywords, the scientific CheMPS2 docs at Psi4 just send users to your docs, just to keep info in only one place. The [interface docs](https://raw.githubusercontent.com/loriab/psi4/0267e9f4a2a850b607028890bb574d1d9fc05955/doc/sphinxman/source/chemps2.rst) will get built properly later today.

Will your versioning scheme allow for a `1.7.28` or `1.7.1` tag so I can pull a non-HEAD version that has the `${LIBC_INTERJECT}` change?

Thanks for merging this so quickly, especially as I've been so slow at polishing up the CheMPS2 integration.

**Comment by SebWouters** [comment]
Hi Lori,

Would '1.8-rc1' work out as well?

I was thinking about making the even numbers LTS and the odd ones feature
and API freezes (no API breaks of any - old and new - features allowed in
odd to even transition)..

So 1.7 would mean the addition of CASPT2 with the corresponding 3-RDM etc.
And 1.8 would be the release after a couple of months of testing, adding
(not changing) interfaces, and fixing bugs and issues.

The actual full 1.8 release is planned mid August. That's the eventual
version you probably want in the long term. But that can be easily adapted
in psi4 as bug fixes go into fedora and debian.

Even if psi4 depends on libchemps2.so.2, there's no problem when I update.

Best wishes,
Sebastian

**Comment by loriab** [comment]
Yes, `1.8rc1` will work nicely, thanks. Your conda page (https://anaconda.org/psi4/chemps2) will also show the rc version (as the psi4 one does for the moment, https://anaconda.org/psi4/psi4) unless you'd like me to adjust that. I realized I can actually work around having a new tag by just pinning to a commit hash, but the tag would be cleaner. Mainly, I'm just trying to get external projects depending on their proper upstream repositories again rather than my forks. :-)

**Comment by SebWouters** [comment]
Hi Lori,

So I opted for v1.7.1 in the end. There are still a couple of things I want to add before going to 1.8-rc1.

https://github.com/SebWouters/CheMPS2/releases/tag/v1.7.1

Best wishes,
Sebastian

**Comment by SebWouters** [comment]
Pushed to the debian alioth git repository:
http://lists.alioth.debian.org/pipermail/debichem-devel/2016-June/007090.html

**Comment by loriab** [comment]
Thanks for the `v1.7.1` tag. conda rebuilt: https://anaconda.org/psi4/pychemps2/files

**Pull request merged**
